exports.CUISINES = [
	{ cuisine: 'Dim Sum' },
	{ cuisine: 'Sandwiches' },
	{ cuisine: 'Southern' },
	{ cuisine: 'Indian' },
	{ cuisine: 'Mexican' },
	{ cuisine: 'Special' },
	{ cuisine: 'Donuts' },
	{ cuisine: 'Burgers' },
	{ cuisine: 'Spanish' },
	{ cuisine: 'Vegetarian' },
	{ cuisine: 'Bakeries' },
	{ cuisine: 'Ethiopian' },
	{ cuisine: 'Cuban' },
	{ cuisine: 'Wine Bars' },
	{ cuisine: 'Seafood' },
	{ cuisine: 'Bagels' },
	{ cuisine: 'Cajun' },
	{ cuisine: 'Juice Bars & Smoothies' },
	{ cuisine: 'Beer' },
	{ cuisine: 'European' },
	{ cuisine: 'Lounges' },
	{ cuisine: 'Cheese' },
	{ cuisine: 'French' },
	{ cuisine: 'Ramen' },
	{ cuisine: 'Italian' },
	{ cuisine: 'Cocktail Bars' },
	{ cuisine: 'Cafes' },
	{ cuisine: 'Pizza' },
	{ cuisine: 'American' },
	{ cuisine: 'German' },
	{ cuisine: 'Korean' },
	{ cuisine: 'Pubs' },
	{ cuisine: 'Chinese' },
	{ cuisine: 'Hot Dogs' },
	{ cuisine: 'Coffee & Tea' },
	{ cuisine: 'Beer Bar' },
	{ cuisine: 'Asian Fusion' },
	{ cuisine: 'Barbeque' },
	{ cuisine: 'Greek' },
	{ cuisine: 'Thai' },
	{ cuisine: 'Diners' },
	{ cuisine: 'Food Stands' },
	{ cuisine: 'Middle Eastern' },
	{ cuisine: 'Caribbean' },
	{ cuisine: 'Mediterranean' },
	{ cuisine: 'Vietnamese' },
	{ cuisine: 'Sushi' },
	{ cuisine: 'Brazilian' },
	{ cuisine: 'Gluten-Free' },
	{ cuisine: 'Food Trucks' },
	{ cuisine: 'Delis' },
	{ cuisine: 'Desserts' },
	{ cuisine: 'Steakhouses' },
	{ cuisine: 'Vegan' },
	{ cuisine: 'Parks' },
	{ cuisine: 'Tex-Mex' },
	{ cuisine: 'Breakfast & Brunch' },
	{ cuisine: 'Chicken Wings' },
	{ cuisine: 'Poke' },
	{ cuisine: 'Latin American' },
	{ cuisine: 'Bars' },
	{ cuisine: 'Japanese' },
	{ cuisine: 'Art' }
];